"""Phase 4: riders, rider documents, rider vehicles, rider availability history, rider locations, rider zones, deliveries, delivery assignments, delivery status history, delivery locations

Revision ID: 32b1ee7f114a
Revises: 50313bec3fbf
Create Date: 2026-09-09 21:52:29.364199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b1ee7f114a'
down_revision = '50313bec3fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='rider_onboarding_status', native_enum=False, length=20), nullable=False),
    sa.Column('operational_status', sa.Enum('OFFLINE', 'AVAILABLE', 'BUSY', name='rider_operational_status', native_enum=False, length=20), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_latitude IS NULL OR (current_latitude >= -90 AND current_latitude <= 90)', name='ck_riders_current_latitude_range'),
    sa.CheckConstraint('current_longitude IS NULL OR (current_longitude >= -180 AND current_longitude <= 180)', name='ck_riders_current_longitude_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riders_location_updated_at'), ['location_updated_at'], unique=False)
        batch_op.create_index('ix_riders_onboarding_operational', ['onboarding_status', 'operational_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_riders_onboarding_status'), ['onboarding_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_riders_operational_status'), ['operational_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_riders_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_riders_user_id'), ['user_id'], unique=True)

    op.create_table('rider_availability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rider_availability_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_availability_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_availability_history_rider_id'), ['rider_id'], unique=False)

    op.create_table('rider_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('GOVERNMENT_ID', 'DRIVERS_LICENSE', 'VEHICLE_REGISTRATION', 'INSURANCE', 'BACKGROUND_CHECK', 'OTHER', name='rider_document_type', native_enum=False, length=30), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='rider_document_verification_status', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rider_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_documents_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rider_documents_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index('ix_rider_documents_rider_status', ['rider_id', 'verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_documents_verification_status'), ['verification_status'], unique=False)

    op.create_table('rider_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_rider_locations_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_rider_locations_longitude_range'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rider_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_locations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_locations_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index('ix_rider_locations_rider_recorded', ['rider_id', 'recorded_at'], unique=False)

    op.create_table('rider_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BICYCLE', 'SCOOTER', 'MOTORCYCLE', 'CAR', 'ON_FOOT', name='rider_vehicle_type', native_enum=False, length=20), nullable=False),
    sa.Column('registration_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='rider_vehicle_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rider_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_vehicles_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rider_vehicles_rider_id'), ['rider_id'], unique=True)

    op.create_table('rider_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('delivery_zone_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='rider_zone_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_zone_id'], ['delivery_zones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rider_id', 'delivery_zone_id', name='uq_rider_zones_rider_zone')
    )
    with op.batch_alter_table('rider_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_zones_delivery_zone_id'), ['delivery_zone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_zones_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rider_zones_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rider_zones_status'), ['status'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SEARCHING', 'OFFERED', 'ASSIGNED', 'PICKED_UP', 'DELIVERING', 'DELIVERED', 'CANCELLED', name='delivery_status', native_enum=False, length=20), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('destination_latitude >= -90 AND destination_latitude <= 90', name='ck_deliveries_dest_lat_range'),
    sa.CheckConstraint('destination_longitude >= -180 AND destination_longitude <= 180', name='ck_deliveries_dest_lng_range'),
    sa.CheckConstraint('pickup_latitude >= -90 AND pickup_latitude <= 90', name='ck_deliveries_pickup_lat_range'),
    sa.CheckConstraint('pickup_longitude >= -180 AND pickup_longitude <= 180', name='ck_deliveries_pickup_lng_range'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_deliveries_branch_status', ['branch_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deliveries_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index('ix_deliveries_rider_status', ['rider_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_status'), ['status'], unique=False)

    op.create_table('delivery_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='delivery_assignment_status', native_enum=False, length=20), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_assignments_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index('ix_delivery_assignments_delivery_status', ['delivery_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_offered_at'), ['offered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_rider_id'), ['rider_id'], unique=False)
        batch_op.create_index('ix_delivery_assignments_rider_status', ['rider_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_assignments_status'), ['status'], unique=False)

    op.create_table('delivery_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('accuracy_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_delivery_locations_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_delivery_locations_longitude_range'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_locations_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index('ix_delivery_locations_delivery_recorded', ['delivery_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_locations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_locations_rider_id'), ['rider_id'], unique=False)

    op.create_table('delivery_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_status_history_changed_by_user_id'), ['changed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_status_history_delivery_id'), ['delivery_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_status_history_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_status_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_delivery_status_history_changed_by_user_id'))

    op.drop_table('delivery_status_history')
    with op.batch_alter_table('delivery_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_locations_rider_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_locations_recorded_at'))
        batch_op.drop_index('ix_delivery_locations_delivery_recorded')
        batch_op.drop_index(batch_op.f('ix_delivery_locations_delivery_id'))

    op.drop_table('delivery_locations')
    with op.batch_alter_table('delivery_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_status'))
        batch_op.drop_index('ix_delivery_assignments_rider_status')
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_rider_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_public_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_offered_at'))
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_expires_at'))
        batch_op.drop_index('ix_delivery_assignments_delivery_status')
        batch_op.drop_index(batch_op.f('ix_delivery_assignments_delivery_id'))

    op.drop_table('delivery_assignments')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_status'))
        batch_op.drop_index('ix_deliveries_rider_status')
        batch_op.drop_index(batch_op.f('ix_deliveries_rider_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_public_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_order_id'))
        batch_op.drop_index('ix_deliveries_branch_status')
        batch_op.drop_index(batch_op.f('ix_deliveries_branch_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('rider_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_zones_status'))
        batch_op.drop_index(batch_op.f('ix_rider_zones_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_zones_public_id'))
        batch_op.drop_index(batch_op.f('ix_rider_zones_delivery_zone_id'))

    op.drop_table('rider_zones')
    with op.batch_alter_table('rider_vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_vehicles_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_vehicles_public_id'))

    op.drop_table('rider_vehicles')
    with op.batch_alter_table('rider_locations', schema=None) as batch_op:
        batch_op.drop_index('ix_rider_locations_rider_recorded')
        batch_op.drop_index(batch_op.f('ix_rider_locations_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_locations_recorded_at'))

    op.drop_table('rider_locations')
    with op.batch_alter_table('rider_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_documents_verification_status'))
        batch_op.drop_index('ix_rider_documents_rider_status')
        batch_op.drop_index(batch_op.f('ix_rider_documents_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_documents_public_id'))

    op.drop_table('rider_documents')
    with op.batch_alter_table('rider_availability_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_availability_history_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_availability_history_changed_at'))

    op.drop_table('rider_availability_history')
    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riders_user_id'))
        batch_op.drop_index(batch_op.f('ix_riders_public_id'))
        batch_op.drop_index(batch_op.f('ix_riders_operational_status'))
        batch_op.drop_index(batch_op.f('ix_riders_onboarding_status'))
        batch_op.drop_index('ix_riders_onboarding_operational')
        batch_op.drop_index(batch_op.f('ix_riders_location_updated_at'))

    op.drop_table('riders')
    # ### end Alembic commands ###
