"""Phase 2: vendors, branches, delivery zones, categories, products, product images, branch products, customer addresses

Revision ID: 3b9c3b4e185c
Revises: b57224c2fee6
Create Date: 2026-09-07 05:50:31.155047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9c3b4e185c'
down_revision = 'b57224c2fee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('recipient_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_customer_addresses_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_customer_addresses_longitude_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_addresses_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_addresses_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_customer_addresses_user_default', ['user_id', 'is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='vendor_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendors_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_user_id'), ['user_id'], unique=True)

    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CLOSED', name='branch_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_branches_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_branches_longitude_range'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_branches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index('ix_branches_vendor_status', ['vendor_id', 'status'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_categories_vendor_active', ['vendor_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='delivery_zone_status', native_enum=False, length=20), nullable=False),
    sa.Column('zone_type', sa.Enum('RADIUS', 'POLYGON', name='delivery_zone_type', native_enum=False, length=20), nullable=False),
    sa.Column('center_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('center_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('radius_meters', sa.Integer(), nullable=True),
    sa.Column('polygon_geojson', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('center_latitude IS NULL OR (center_latitude >= -90 AND center_latitude <= 90)', name='ck_delivery_zones_center_latitude_range'),
    sa.CheckConstraint('center_longitude IS NULL OR (center_longitude >= -180 AND center_longitude <= 180)', name='ck_delivery_zones_center_longitude_range'),
    sa.CheckConstraint('radius_meters IS NULL OR radius_meters > 0', name='ck_delivery_zones_radius_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_zones_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_delivery_zones_branch_status', ['branch_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_zones_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_zones_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='product_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_products_category_status', ['category_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('branch_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='branch_product_availability', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price_override IS NULL OR price_override >= 0', name='ck_branch_products_price_override_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_branch_products_branch_product')
    )
    with op.batch_alter_table('branch_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_products_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index('ix_branch_products_branch_availability', ['branch_id', 'availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_products_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_products_public_id'), ['public_id'], unique=True)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_images_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_public_id'))
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('branch_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_products_public_id'))
        batch_op.drop_index(batch_op.f('ix_branch_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_branch_products_branch_id'))
        batch_op.drop_index('ix_branch_products_branch_availability')
        batch_op.drop_index(batch_op.f('ix_branch_products_availability_status'))

    op.drop_table('branch_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_public_id'))
        batch_op.drop_index('ix_products_category_status')
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_zones_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_zones_public_id'))
        batch_op.drop_index('ix_delivery_zones_branch_status')
        batch_op.drop_index(batch_op.f('ix_delivery_zones_branch_id'))

    op.drop_table('delivery_zones')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_vendor_id'))
        batch_op.drop_index('ix_categories_vendor_active')
        batch_op.drop_index(batch_op.f('ix_categories_public_id'))
        batch_op.drop_index(batch_op.f('ix_categories_is_active'))

    op.drop_table('categories')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index('ix_branches_vendor_status')
        batch_op.drop_index(batch_op.f('ix_branches_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_branches_status'))
        batch_op.drop_index(batch_op.f('ix_branches_public_id'))

    op.drop_table('branches')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_user_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_status'))
        batch_op.drop_index(batch_op.f('ix_vendors_public_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('customer_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_addresses_user_id'))
        batch_op.drop_index('ix_customer_addresses_user_default')
        batch_op.drop_index(batch_op.f('ix_customer_addresses_public_id'))
        batch_op.drop_index(batch_op.f('ix_customer_addresses_is_default'))

    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
