"""Phase 7: support tickets, disputes, admin RBAC, audit extension, reports

Revision ID: 540d85f4fe91
Revises: b5f0e2b2665a
Create Date: 2026-09-13 05:06:00.793682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540d85f4fe91'
down_revision = 'b5f0e2b2665a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_permissions_key'), ['key'], unique=True)

    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='admin_role_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_roles_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_roles_public_id'), ['public_id'], unique=True)

    op.create_table('admin_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('report_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('report_type', sa.Enum('ORDERS', 'FINANCE', 'VENDORS', 'RIDERS', 'DELIVERY', 'CUSTOMERS', 'PROMOTIONS_ADS', 'SUPPORT_DISPUTES', name='report_type', native_enum=False, length=25), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('access_level', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_definitions_public_id'), ['public_id'], unique=True)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('ORDER_ISSUE', 'PAYMENT_ISSUE', 'DELIVERY_ISSUE', 'ACCOUNT_ISSUE', 'VENDOR_ISSUE', 'RIDER_ISSUE', 'GENERAL', 'OTHER', name='ticket_category', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='ticket_priority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_FOR_CUSTOMER', 'RESOLVED', 'CLOSED', name='ticket_status', native_enum=False, length=25), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('related_entity_type', sa.Enum('ORDER', 'DELIVERY', 'PAYMENT', 'REFUND', 'VENDOR', 'RIDER', name='related_entity_type', native_enum=False, length=20), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index('ix_support_tickets_agent_status', ['assigned_agent_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_tickets_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index('ix_support_tickets_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('report_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_definition_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=25), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='report_export_status', native_enum=False, length=15), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_definition_id'], ['report_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_exports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_exports_report_definition_id'), ['report_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_exports_status'), ['status'], unique=False)

    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'INTERNAL', name='message_visibility', native_enum=False, length=10), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_visibility'), ['visibility'], unique=False)

    op.create_table('support_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['support_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_attachments_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_attachments_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_support_attachments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_number', sa.String(length=20), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('refund_id', sa.Integer(), nullable=True),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('MISSING_ITEM', 'WRONG_ITEM', 'DAMAGED_ITEM', 'LATE_DELIVERY', 'FAILED_DELIVERY', 'PAYMENT_ISSUE', 'SERVICE_COMPLAINT', 'OTHER', name='dispute_category', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='dispute_priority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'ACTION_REQUIRED', 'RESOLVED', 'REJECTED', 'CLOSED', name='dispute_status', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_dispute_number'), ['dispute_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_disputes_opened_by'), ['opened_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_disputes_refund_id'), ['refund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)
        batch_op.create_index('ix_disputes_status_priority', ['status', 'priority'], unique=False)

    op.create_table('dispute_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('NOTE', 'REQUEST_INFO', 'REFUND_ISSUED', 'PARTIAL_REFUND_ISSUED', 'REPLACEMENT_APPROVED', 'ESCALATED', 'REJECTED', 'RESOLVED', 'REOPENED', 'OTHER', name='dispute_action_type', native_enum=False, length=25), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', name='dispute_action_status', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispute_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_actions_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispute_actions_dispute_id'), ['dispute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispute_actions_public_id'), ['public_id'], unique=True)

    op.create_table('dispute_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=False),
    sa.Column('secure_reference', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispute_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_evidence_dispute_id'), ['dispute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispute_evidence_public_id'), ['public_id'], unique=True)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('before_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('after_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_metadata', sa.Text(), nullable=True))
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_admin_role_id'), ['admin_role_id'], unique=False)
        batch_op.create_foreign_key('fk_users_admin_role_id_admin_roles', 'admin_roles', ['admin_role_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_admin_role_id_admin_roles', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_admin_role_id'))
        batch_op.drop_column('admin_role_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_column('event_metadata')
        batch_op.drop_column('after_data')
        batch_op.drop_column('before_data')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('dispute_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_evidence_public_id'))
        batch_op.drop_index(batch_op.f('ix_dispute_evidence_dispute_id'))

    op.drop_table('dispute_evidence')
    with op.batch_alter_table('dispute_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_actions_public_id'))
        batch_op.drop_index(batch_op.f('ix_dispute_actions_dispute_id'))
        batch_op.drop_index(batch_op.f('ix_dispute_actions_actor_id'))

    op.drop_table('dispute_actions')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index('ix_disputes_status_priority')
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_refund_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_public_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_priority'))
        batch_op.drop_index(batch_op.f('ix_disputes_payment_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_order_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_opened_by'))
        batch_op.drop_index(batch_op.f('ix_disputes_dispute_number'))
        batch_op.drop_index(batch_op.f('ix_disputes_delivery_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('support_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_attachments_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_attachments_public_id'))
        batch_op.drop_index(batch_op.f('ix_support_attachments_message_id'))

    op.drop_table('support_attachments')
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_visibility'))
        batch_op.drop_index(batch_op.f('ix_support_messages_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_public_id'))

    op.drop_table('support_messages')
    with op.batch_alter_table('report_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_exports_status'))
        batch_op.drop_index(batch_op.f('ix_report_exports_requested_by'))
        batch_op.drop_index(batch_op.f('ix_report_exports_report_definition_id'))
        batch_op.drop_index(batch_op.f('ix_report_exports_public_id'))

    op.drop_table('report_exports')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_ticket_number'))
        batch_op.drop_index('ix_support_tickets_status_priority')
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_requester_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_public_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_assigned_agent_id'))
        batch_op.drop_index('ix_support_tickets_agent_status')

    op.drop_table('support_tickets')
    with op.batch_alter_table('report_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_definitions_public_id'))

    op.drop_table('report_definitions')
    op.drop_table('admin_role_permissions')
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_roles_public_id'))
        batch_op.drop_index(batch_op.f('ix_admin_roles_name'))

    op.drop_table('admin_roles')
    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_permissions_key'))

    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
