"""Phase 5: payments, commissions, ledger, wallets, payouts, refunds

Revision ID: a3fcdcf0e10f
Revises: 32b1ee7f114a
Create Date: 2026-09-11 03:52:23.804632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fcdcf0e10f'
down_revision = '32b1ee7f114a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('percentage_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('scope_type', sa.Enum('GLOBAL', 'VENDOR', 'CATEGORY', name='commission_scope_type', native_enum=False, length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='commission_rule_status', native_enum=False, length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fixed_amount >= 0', name='ck_commission_rules_fixed_non_negative'),
    sa.CheckConstraint('percentage_rate >= 0 AND percentage_rate <= 1', name='ck_commission_rules_rate_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_rules_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_commission_rules_scope_status', ['scope_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rules_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_rules_status'), ['status'], unique=False)

    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('CUSTOMER_CLEARING', 'PLATFORM_CLEARING', 'PLATFORM_REVENUE', 'PLATFORM_PAYOUT_SETTLEMENT', 'VENDOR_PAYABLE', 'RIDER_PAYABLE', name='financial_account_type', native_enum=False, length=30), nullable=False),
    sa.Column('owner_type', sa.Enum('PLATFORM', 'CUSTOMER', 'VENDOR', 'RIDER', name='financial_account_owner_type', native_enum=False, length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='financial_account_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_type', 'owner_type', 'owner_id', 'currency', name='uq_financial_accounts_identity')
    )
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_accounts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_accounts_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_accounts_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_financial_accounts_type_owner', ['account_type', 'owner_id'], unique=False)

    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT_CAPTURE', 'ORDER_SETTLEMENT', 'REFUND', 'VENDOR_PAYOUT', 'WALLET_ADJUSTMENT', name='financial_transaction_type', native_enum=False, length=30), nullable=False),
    sa.Column('reference_type', sa.Enum('PAYMENT', 'ORDER', 'REFUND', 'VENDOR_PAYOUT', 'WALLET_ADJUSTMENT', name='financial_reference_type', native_enum=False, length=20), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'REVERSED', name='financial_transaction_status', native_enum=False, length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'idempotency_key', name='uq_financial_transactions_type_idempotency_key')
    )
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_financial_transactions_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transactions_type'), ['type'], unique=False)

    op.create_table('commission_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('commission_rule_id', sa.Integer(), nullable=True),
    sa.Column('rate_snapshot', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fixed_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('calculated_amount >= 0', name='ck_commission_snapshots_amount_non_negative'),
    sa.ForeignKeyConstraint(['commission_rule_id'], ['commission_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['financial_transaction_id'], ['financial_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_snapshots_commission_rule_id'), ['commission_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commission_snapshots_financial_transaction_id'), ['financial_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_commission_snapshots_public_id'), ['public_id'], unique=True)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='ledger_entry_type', native_enum=False, length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_transaction_id'], ['financial_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_entries_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_financial_transaction_id'), ['financial_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_public_id'), ['public_id'], unique=True)

    op.create_table('rider_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('financial_account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cached_available_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cached_pending_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='rider_wallet_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cached_available_balance >= 0', name='ck_rider_wallets_available_non_negative'),
    sa.CheckConstraint('cached_pending_balance >= 0', name='ck_rider_wallets_pending_non_negative'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_account_id')
    )
    with op.batch_alter_table('rider_wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rider_wallets_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rider_wallets_rider_id'), ['rider_id'], unique=True)

    op.create_table('vendor_financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('financial_account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cached_payable_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='vendor_account_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cached_payable_balance >= 0', name='ck_vendor_financial_accounts_balance_non_negative'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_account_id')
    )
    with op.batch_alter_table('vendor_financial_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_financial_accounts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendor_financial_accounts_vendor_id'), ['vendor_id'], unique=True)

    op.create_table('vendor_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='vendor_payout_status', native_enum=False, length=20), nullable=False),
    sa.Column('destination_reference', sa.String(length=255), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_vendor_payouts_amount_positive'),
    sa.ForeignKeyConstraint(['vendor_account_id'], ['vendor_financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'idempotency_key', name='uq_vendor_payouts_vendor_idempotency_key')
    )
    with op.batch_alter_table('vendor_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payouts_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payouts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendor_payouts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payouts_vendor_account_id'), ['vendor_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_payouts_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index('ix_vendor_payouts_vendor_status', ['vendor_id', 'status'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EARNING', 'ADJUSTMENT_CREDIT', 'ADJUSTMENT_DEBIT', 'PAYOUT_DEBIT', name='wallet_transaction_type', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('POSTED', name='wallet_transaction_status', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_wallet_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['financial_transaction_id'], ['financial_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['rider_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_financial_transaction_id'), ['financial_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_wallet_id'), ['wallet_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'PARTIALLY_REFUNDED', 'REFUNDED', name='payment_status', native_enum=False, length=20), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'idempotency_key', name='uq_payments_customer_idempotency_key')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_payments_order_status', ['order_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_provider_reference'), ['provider_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CHARGE', 'VERIFY', 'REFUND', name='payment_transaction_type', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payment_transaction_status', native_enum=False, length=20), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_external_event_id'), ['external_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index('ix_payment_transactions_payment_type', ['payment_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_type'), ['type'], unique=False)

    op.create_table('payment_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('payload_reference', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('PROCESSED', 'IGNORED', 'REJECTED', name='webhook_processing_status', native_enum=False, length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_webhook_events_provider_external_id')
    )
    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_webhook_events_public_id'), ['public_id'], unique=True)

    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'PROCESSING', 'SUCCEEDED', 'FAILED', name='refund_status', native_enum=False, length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_refunds_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requested_by_user_id', 'idempotency_key', name='uq_refunds_requester_idempotency_key')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index('ix_refunds_payment_status', ['payment_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_refunds_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_status'))
        batch_op.drop_index(batch_op.f('ix_refunds_public_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_provider_reference'))
        batch_op.drop_index('ix_refunds_payment_status')
        batch_op.drop_index(batch_op.f('ix_refunds_payment_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_order_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('payment_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_public_id'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_provider'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_processing_status'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_webhook_events_created_at'))

    op.drop_table('payment_webhook_events')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_reference'))
        batch_op.drop_index('ix_payment_transactions_payment_type')
        batch_op.drop_index(batch_op.f('ix_payment_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_external_event_id'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_public_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_reference'))
        batch_op.drop_index('ix_payments_order_status')
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_wallet_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_financial_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('vendor_payouts', schema=None) as batch_op:
        batch_op.drop_index('ix_vendor_payouts_vendor_status')
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_vendor_account_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_public_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_provider_reference'))

    op.drop_table('vendor_payouts')
    with op.batch_alter_table('vendor_financial_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_financial_accounts_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_financial_accounts_public_id'))

    op.drop_table('vendor_financial_accounts')
    with op.batch_alter_table('rider_wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rider_wallets_rider_id'))
        batch_op.drop_index(batch_op.f('ix_rider_wallets_public_id'))

    op.drop_table('rider_wallets')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_public_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_financial_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_account_id'))
        batch_op.drop_index('ix_ledger_entries_account_created')

    op.drop_table('ledger_entries')
    with op.batch_alter_table('commission_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_snapshots_public_id'))
        batch_op.drop_index(batch_op.f('ix_commission_snapshots_financial_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_commission_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_commission_snapshots_commission_rule_id'))

    op.drop_table('commission_snapshots')
    with op.batch_alter_table('financial_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_reference_type'))
        batch_op.drop_index(batch_op.f('ix_financial_transactions_reference_id'))
        batch_op.drop_index('ix_financial_transactions_reference')
        batch_op.drop_index(batch_op.f('ix_financial_transactions_public_id'))

    op.drop_table('financial_transactions')
    with op.batch_alter_table('financial_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_financial_accounts_type_owner')
        batch_op.drop_index(batch_op.f('ix_financial_accounts_public_id'))
        batch_op.drop_index(batch_op.f('ix_financial_accounts_owner_type'))
        batch_op.drop_index(batch_op.f('ix_financial_accounts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_financial_accounts_account_type'))

    op.drop_table('financial_accounts')
    with op.batch_alter_table('commission_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_rules_status'))
        batch_op.drop_index(batch_op.f('ix_commission_rules_scope_type'))
        batch_op.drop_index('ix_commission_rules_scope_status')
        batch_op.drop_index(batch_op.f('ix_commission_rules_public_id'))

    op.drop_table('commission_rules')
    # ### end Alembic commands ###
