"""Phase 6: promotions, advertising, reviews, notifications

Revision ID: b5f0e2b2665a
Revises: a3fcdcf0e10f
Create Date: 2026-09-11 21:16:36.859532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f0e2b2665a'
down_revision = 'a3fcdcf0e10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notification_channel', native_enum=False, length=10), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='notification_template_status', native_enum=False, length=10), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'channel', name='uq_notification_templates_key_channel')
    )
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_public_id'), ['public_id'], unique=True)

    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ORDER', 'PAYMENT', 'DELIVERY', 'PROMOTION', 'REVIEW', 'PAYOUT', 'ADVERTISING', 'ACCOUNT', name='notification_category', native_enum=False, length=20), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', name='notification_preference_channel', native_enum=False, length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'channel', name='uq_notification_preferences_identity')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ORDER', 'PAYMENT', 'DELIVERY', 'PROMOTION', 'REVIEW', 'PAYOUT', 'ADVERTISING', 'ACCOUNT', name='notification_category', native_enum=False, length=20), nullable=False),
    sa.Column('template_key', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_notifications_recipient_created', ['recipient_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_recipient_read', ['recipient_user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    op.create_table('ad_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('objective', sa.Enum('SPONSORED_LISTING', 'BANNER', name='ad_objective', native_enum=False, length=20), nullable=False),
    sa.Column('target_type', sa.Enum('VENDOR', 'BRANCH', 'PRODUCT', 'CATEGORY', name='ad_target_type', native_enum=False, length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('pricing_model', sa.Enum('CPC', 'CPM', name='ad_pricing_model', native_enum=False, length=10), nullable=False),
    sa.Column('bid_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('spent_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'PAUSED', 'BUDGET_EXHAUSTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='ad_campaign_status', native_enum=False, length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bid_amount > 0', name='ck_ad_campaigns_bid_amount_positive'),
    sa.CheckConstraint('spent_total >= 0', name='ck_ad_campaigns_spent_non_negative'),
    sa.CheckConstraint('total_budget > 0', name='ck_ad_campaigns_total_budget_positive'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_campaigns_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ad_campaigns_status'), ['status'], unique=False)
        batch_op.create_index('ix_ad_campaigns_target', ['target_type', 'target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_campaigns_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index('ix_ad_campaigns_vendor_status', ['vendor_id', 'status'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', name='notification_delivery_channel', native_enum=False, length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_delivery_status', native_enum=False, length=10), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_status'), ['status'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_DELIVERY', name='promotion_type', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scope_type', sa.Enum('ORDER', 'VENDOR', 'BRANCH', 'CATEGORY', 'PRODUCT', name='promotion_scope_type', native_enum=False, length=20), nullable=False),
    sa.Column('usage_limit_total', sa.Integer(), nullable=True),
    sa.Column('usage_limit_per_customer', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('stacking_policy', sa.Enum('EXCLUSIVE', name='promotion_stacking_policy', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'ARCHIVED', name='promotion_status', native_enum=False, length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_promotions_value_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promotions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_promotions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotions_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index('ix_promotions_vendor_status', ['vendor_id', 'status'], unique=False)

    op.create_table('ad_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('IMPRESSION', 'CLICK', name='ad_event_type', native_enum=False, length=20), nullable=False),
    sa.Column('viewer_user_id', sa.Integer(), nullable=True),
    sa.Column('event_reference', sa.String(length=128), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'event_reference', name='uq_ad_events_campaign_reference')
    )
    with op.batch_alter_table('ad_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_ad_events_campaign_type', ['campaign_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_events_public_id'), ['public_id'], unique=True)

    op.create_table('promotion_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('FIRST_ORDER_ONLY', 'MIN_ITEM_COUNT', name='promotion_rule_type', native_enum=False, length=30), nullable=False),
    sa.Column('rule_value', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'rule_type', name='uq_promotion_rules_identity')
    )
    with op.batch_alter_table('promotion_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_rules_promotion_id'), ['promotion_id'], unique=False)

    op.create_table('promotion_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'target_id', name='uq_promotion_scopes_identity')
    )
    with op.batch_alter_table('promotion_scopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_scopes_promotion_id'), ['promotion_id'], unique=False)

    op.create_table('order_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('code_snapshot', sa.String(length=40), nullable=True),
    sa.Column('name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('type_snapshot', sa.String(length=20), nullable=False),
    sa.Column('value_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_order_promotions_discount_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_promotions_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_promotions_promotion_id'), ['promotion_id'], unique=False)

    op.create_table('promotion_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CONSUMED', 'RELEASED', name='promotion_usage_status', native_enum=False, length=20), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_usages_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usages_order_id'), ['order_id'], unique=True)
        batch_op.create_index('ix_promotion_usages_promotion_customer', ['promotion_id', 'customer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usages_promotion_id'), ['promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_usages_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_promotion_usages_status'), ['status'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('VENDOR', 'RIDER', 'PRODUCT', name='review_target_type', native_enum=False, length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'PENDING_REVIEW', 'HIDDEN', 'REMOVED', name='review_status', native_enum=False, length=20), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'order_id', 'target_type', 'target_id', name='uq_reviews_identity')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_target_id'), ['target_id'], unique=False)
        batch_op.create_index('ix_reviews_target_status', ['target_type', 'target_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_target_type'), ['target_type'], unique=False)

    op.create_table('review_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'DISMISSED', name='review_report_status', native_enum=False, length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'reporter_user_id', name='uq_review_reports_identity')
    )
    with op.batch_alter_table('review_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reports_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_reports_reporter_user_id'), ['reporter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_reports_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_reports_status'), ['status'], unique=False)

    op.create_table('review_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('responder_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PUBLISHED', 'HIDDEN', name='review_response_status', native_enum=False, length=20), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responder_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_responses_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_responses_review_id'), ['review_id'], unique=True)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_promotion_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_carts_applied_promotion_id'), ['applied_promotion_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_carts_applied_promotion_id_promotions', 'promotions', ['applied_promotion_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_total', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=False))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_average')

    with op.batch_alter_table('riders', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_average')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_average')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_total')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_carts_applied_promotion_id_promotions', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_carts_applied_promotion_id'))
        batch_op.drop_column('applied_promotion_id')

    with op.batch_alter_table('review_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_responses_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_responses_public_id'))

    op.drop_table('review_responses')
    with op.batch_alter_table('review_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_reports_status'))
        batch_op.drop_index(batch_op.f('ix_review_reports_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_reports_reporter_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_reports_public_id'))

    op.drop_table('review_reports')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_target_type'))
        batch_op.drop_index('ix_reviews_target_status')
        batch_op.drop_index(batch_op.f('ix_reviews_target_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_reviews_public_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_customer_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('promotion_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_usages_status'))
        batch_op.drop_index(batch_op.f('ix_promotion_usages_public_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usages_promotion_id'))
        batch_op.drop_index('ix_promotion_usages_promotion_customer')
        batch_op.drop_index(batch_op.f('ix_promotion_usages_order_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_usages_customer_id'))

    op.drop_table('promotion_usages')
    with op.batch_alter_table('order_promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_promotions_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_order_promotions_order_id'))

    op.drop_table('order_promotions')
    with op.batch_alter_table('promotion_scopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_scopes_promotion_id'))

    op.drop_table('promotion_scopes')
    with op.batch_alter_table('promotion_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_rules_promotion_id'))

    op.drop_table('promotion_rules')
    with op.batch_alter_table('ad_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_events_public_id'))
        batch_op.drop_index(batch_op.f('ix_ad_events_event_type'))
        batch_op.drop_index('ix_ad_events_campaign_type')
        batch_op.drop_index(batch_op.f('ix_ad_events_campaign_id'))

    op.drop_table('ad_events')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index('ix_promotions_vendor_status')
        batch_op.drop_index(batch_op.f('ix_promotions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_status'))
        batch_op.drop_index(batch_op.f('ix_promotions_public_id'))
        batch_op.drop_index(batch_op.f('ix_promotions_code'))

    op.drop_table('promotions')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_public_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_notification_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('ad_campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_ad_campaigns_vendor_status')
        batch_op.drop_index(batch_op.f('ix_ad_campaigns_vendor_id'))
        batch_op.drop_index('ix_ad_campaigns_target')
        batch_op.drop_index(batch_op.f('ix_ad_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_ad_campaigns_public_id'))

    op.drop_table('ad_campaigns')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index('ix_notifications_recipient_read')
        batch_op.drop_index('ix_notifications_recipient_created')
        batch_op.drop_index(batch_op.f('ix_notifications_public_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_public_id'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_key'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_channel'))

    op.drop_table('notification_templates')
    # ### end Alembic commands ###
